"""Add peer review versioning audit logs and doi

Revision ID: 9e2723e72340
Revises: dd41a56c28a5
Create Date: 2026-07-09 05:28:50.036009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2723e72340'
down_revision: Union[str, Sequence[str], None] = 'dd41a56c28a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('doi', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('version', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_submissions_doi'), 'submissions', ['doi'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_doi'), table_name='submissions')
    op.drop_column('submissions', 'version')
    op.drop_column('submissions', 'doi')
    # ### end Alembic commands ###
